spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: employee-management
        predicates:
        - Path=/**
        uri: lb://employee-management
server:
  port: 8711
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost